//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 12:24:52 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.springintegration.barrak.org/esbdt/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.barrak.springintegration.webservice.esbdt.schemas;
