//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.15 at 12:24:52 PM CET 
//


package org.barrak.springintegration.webservice.esbdt.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SRIGenericRequest2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SRIGenericRequest2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attr2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="attr3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attr4" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="attr5" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SRIGenericRequest2", propOrder = {
    "attr1",
    "attr2",
    "attr3",
    "attr4",
    "attr5"
})
public class SRIGenericRequest2 {

    @XmlElement(required = true)
    protected String attr1;
    protected int attr2;
    @XmlElement(required = true)
    protected String attr3;
    protected int attr4;
    protected int attr5;

    /**
     * Gets the value of the attr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * Sets the value of the attr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttr1(String value) {
        this.attr1 = value;
    }

    /**
     * Gets the value of the attr2 property.
     * 
     */
    public int getAttr2() {
        return attr2;
    }

    /**
     * Sets the value of the attr2 property.
     * 
     */
    public void setAttr2(int value) {
        this.attr2 = value;
    }

    /**
     * Gets the value of the attr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * Sets the value of the attr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttr3(String value) {
        this.attr3 = value;
    }

    /**
     * Gets the value of the attr4 property.
     * 
     */
    public int getAttr4() {
        return attr4;
    }

    /**
     * Sets the value of the attr4 property.
     * 
     */
    public void setAttr4(int value) {
        this.attr4 = value;
    }

    /**
     * Gets the value of the attr5 property.
     * 
     */
    public int getAttr5() {
        return attr5;
    }

    /**
     * Sets the value of the attr5 property.
     * 
     */
    public void setAttr5(int value) {
        this.attr5 = value;
    }

}
